#!/usr/bin/env python3
"""
Minimal Attio REST client used by the outreach loop.

Usage:
    from scripts.attio_client import AttioClient
    c = AttioClient(schema_path="~/.config/claude-outreach-loop/schema.json")
    c.update_list_entry(entry_id, {"to_research": "Outreach Sent", ...})

The client reads `schema.json` (generated by `scripts/setup.py`) to know which
attribute is the STATUS field (used by the Kanban) and the type of every other
field, so values are wrapped correctly (status → bare string, select → option
ID, everything else → [{"value": ...}]).
"""
import json
import os
import socket
import urllib.error
import urllib.parse
import urllib.request
from datetime import date, timedelta


class AttioError(RuntimeError):
    """Raised for Attio API errors. Includes the HTTP status code when known."""

    def __init__(self, message, status=None, code=None):
        super().__init__(message)
        self.status = status
        self.code = code


class AttioClient:
    API = "https://api.attio.com/v2"
    TIMEOUT = 30

    def __init__(self, api_key=None, list_id=None, schema_path=None):
        self.api_key = api_key or os.environ.get("ATTIO_API_KEY")
        if not self.api_key:
            raise AttioError("ATTIO_API_KEY not set — export it or pass api_key=")
        self.list_id = list_id or os.environ.get("ATTIO_LIST_ID")
        self.H = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        self.schema = None
        if schema_path:
            schema_path = os.path.expanduser(schema_path)
            try:
                with open(schema_path) as f:
                    self.schema = json.load(f)
            except FileNotFoundError:
                raise AttioError(
                    f"schema not found at {schema_path}. Run `python3 scripts/setup.py` first."
                )

    def _request(self, method, path, body=None):
        url = f"{self.API}{path}"
        data = json.dumps(body).encode() if body else None
        req = urllib.request.Request(url, data=data, headers=self.H, method=method)
        try:
            with urllib.request.urlopen(req, timeout=self.TIMEOUT) as r:
                raw = r.read()
                return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as e:
            body_text = e.read().decode(errors="replace")
            # Try to extract Attio's error code; strip verbose bodies to avoid leaking secrets in logs.
            err_code = None
            try:
                err_code = json.loads(body_text).get("code")
            except (ValueError, AttributeError):
                pass
            raise AttioError(
                f"{method} {path} failed: HTTP {e.code} code={err_code}",
                status=e.code,
                code=err_code,
            ) from None
        except urllib.error.URLError as e:
            raise AttioError(f"{method} {path} failed: network error: {e.reason}") from None
        except (TimeoutError, socket.timeout):
            raise AttioError(f"{method} {path} failed: timeout (>{self.TIMEOUT}s)") from None

    # --- Schema helpers ---

    def _status_slug(self):
        if not self.schema:
            return None
        return self.schema.get("status_slug") or next(
            (s for s, t in self.schema.get("types", {}).items() if t == "status"),
            None,
        )

    def _wrap_entry_value(self, slug, value):
        """Wrap a value in the right shape given the attribute type from schema."""
        if not self.schema:
            # No schema loaded — pass through as-is; callers are expected to wrap correctly.
            return value
        atype = self.schema.get("types", {}).get(slug)
        if atype == "status":
            return value if isinstance(value, str) else value
        if atype == "select":
            if isinstance(value, str):
                opt_id = self.schema.get("options", {}).get(slug, {}).get(value)
                if opt_id:
                    return [{"option": opt_id}]
                return [{"option": value}]
            return value
        if atype in ("number", "text", "date", "datetime", "currency", "checkbox", "rating", "timestamp"):
            if isinstance(value, (str, int, float, bool)):
                return [{"value": value}]
        return value

    # --- Records ---

    def create_company(self, name, domain=None, description=None, linkedin=None):
        values = {"name": [{"value": name}]}
        if domain:
            values["domains"] = [{"domain": domain}]
        if description:
            values["description"] = [{"value": description}]
        if linkedin:
            if not linkedin.startswith("http"):
                linkedin = f"https://{linkedin.lstrip('/')}"
            values["linkedin"] = [{"value": linkedin}]
        try:
            r = self._request("POST", "/objects/companies/records", {"data": {"values": values}})
            return r["data"]["id"]["record_id"]
        except AttioError as e:
            # On 409 (domain conflict) look up the existing record and return its id.
            if e.status == 409 and domain:
                q = {"filter": {"domains": {"domain": {"$eq": domain}}}, "limit": 1}
                existing = self._request("POST", "/objects/companies/records/query", q)
                data = existing.get("data") or []
                if data:
                    return data[0]["id"]["record_id"]
            raise

    def create_person(self, first, last, title=None, linkedin=None, company_id=None, description=None, email=None):
        if not first or not last:
            raise AttioError("create_person requires both first and last names")
        values = {
            "name": [{"first_name": first, "last_name": last, "full_name": f"{first} {last}"}],
        }
        if title:
            values["job_title"] = [{"value": title}]
        if linkedin:
            if not linkedin.startswith("http"):
                linkedin = f"https://{linkedin.lstrip('/')}"
            values["linkedin"] = [{"value": linkedin}]
        if company_id:
            values["company"] = [{"target_object": "companies", "target_record_id": company_id}]
        if description:
            values["description"] = [{"value": description}]
        if email:
            values["email_addresses"] = [{"email_address": email}]
        r = self._request("POST", "/objects/people/records", {"data": {"values": values}})
        return r["data"]["id"]["record_id"]

    def update_record(self, obj_slug, record_id, values):
        if not record_id:
            raise AttioError("update_record requires a record_id")
        return self._request("PATCH", f"/objects/{obj_slug}/records/{record_id}", {"data": {"values": values}})

    # --- List entries ---

    def list_entries(self, list_id=None):
        """Fetch all entries from the list, paginating automatically."""
        list_id = list_id or self.list_id
        entries = []
        offset = 0
        page_size = 500
        while True:
            r = self._request(
                "POST",
                f"/lists/{list_id}/entries/query",
                {"limit": page_size, "offset": offset},
            )
            page = r.get("data", [])
            entries.extend(page)
            if len(page) < page_size:
                break
            offset += page_size
        return entries

    def create_list_entry(self, parent_object, parent_record_id, entry_values, list_id=None):
        if not parent_record_id:
            raise AttioError("create_list_entry requires a parent_record_id")
        list_id = list_id or self.list_id
        body = {"data": {
            "parent_object": parent_object,
            "parent_record_id": parent_record_id,
            "entry_values": entry_values,
        }}
        r = self._request("POST", f"/lists/{list_id}/entries", body)
        return r["data"]["id"]["entry_id"]

    def update_list_entry(self, entry_id, entry_values, list_id=None):
        """Patch a list entry's values. Uses schema to wrap values correctly per attribute type.

        For status-type fields: pass a plain string (the status title).
        For select-type fields: pass a plain string and the client resolves to option_id.
        For scalar fields (number, date, text): pass a plain value or an already-wrapped list.
        """
        if not entry_id:
            raise AttioError("update_list_entry requires an entry_id")
        list_id = list_id or self.list_id
        wrapped = {slug: self._wrap_entry_value(slug, v) for slug, v in entry_values.items()}
        return self._request(
            "PATCH",
            f"/lists/{list_id}/entries/{entry_id}",
            {"data": {"entry_values": wrapped}},
        )

    def delete_list_entry(self, entry_id, list_id=None):
        if not entry_id:
            raise AttioError("delete_list_entry requires an entry_id")
        list_id = list_id or self.list_id
        return self._request("DELETE", f"/lists/{list_id}/entries/{entry_id}")

    # --- Notes ---

    def create_note(self, parent_object, parent_record_id, title, content, fmt="plaintext"):
        if not parent_record_id:
            raise AttioError("create_note requires a parent_record_id")
        body = {"data": {
            "parent_object": parent_object,
            "parent_record_id": parent_record_id,
            "title": title,
            "format": fmt,
            "content": content,
        }}
        r = self._request("POST", "/notes", body)
        return r["data"]["id"]["note_id"]

    # --- Convenience: log an outreach touch ---

    def log_touch(self, entry_id, person_record_id, status, channel, message, attempt=1, followup_days=3):
        """All-in-one: update list entry status + log a note on the person.

        `status` is the status title (e.g., "Outreach Sent"). The client reads the
        discovered status slug from schema and writes there — do not pass a slug.
        """
        status_slug = self._status_slug()
        if not status_slug:
            raise AttioError(
                "no STATUS slug known — run scripts/setup.py to discover your list's schema "
                "or set 'status_slug' in schema.json manually"
            )

        today = date.today().isoformat()
        followup = (date.today() + timedelta(days=followup_days)).isoformat()

        self.update_list_entry(entry_id, {
            status_slug: status,
            "attempt_number": attempt,
            "last_touch": today,
            "next_followup_due": followup,
        })

        self.create_note(
            parent_object="people",
            parent_record_id=person_record_id,
            title=f"LinkedIn {channel} sent {today}",
            content=f"Sent on {today}:\n\n{message}\n\nNext follow-up: {followup}",
        )
